config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#index'
    resources :blogs, only: [:new, :index ,:create, :show, :edit, :destroy] do
      resources :entries, only: [:new, :create, :show, :edit, :destroy] do
        resources :comments, only: [:create, :update, :destroy]
      end
    end
  #  if Rails.env.development?
  #   mount LetterOpener::Engine, at: '/letter_opener'
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_many :entries

    validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :entry
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :blog
    has_many :comments
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blogs = Blog.all
		@q = Blog.ransack(params[:q])
		@blogs = @q.result
	end

	def new; end

	def create
		Blog.create(blog_params)
		redirect_to blogs_path
	end

	def show
		@blog = Blog.find(params[:id])
	end

	def edit; end

	def destroy
		@blog = Blog.find(params[:id])
		@blog.destroy
		redirect_to root_path
	end

	private
	def blog_params
		params.require(:blog).permit(:title)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new; end

	def create
		@blog = Blog.find(params[:blog_id])
		comment = Comment.new(comment_params)
		p comment_params
		comment.entry_id = params[:entry_id]
		p params[:entry_id]
		# comment.save
		if comment.save
			NoticeMailer.sendmail_confirm(comment).deliver_later
			redirect_to blog_entry_path(@blog, comment.entry)
		else
			render 'new'
		end
	end

	def update
		@blog = Blog.find(params[:blog_id])
		@comment = Comment.find(params[:id])
		@comment.status = "approved"
		@comment.save
		redirect_to blog_entry_path(@blog, @comment.entry)
	end

	def destroy
		@blog = Blog.find(params[:blog_id])
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to blog_entry_path(@blog, @comment.entry)
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :status)
	end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def new; end

	def create
		entry = Entry.new(entry_params)
		entry.blog_id = params[:blog_id]
		p params[:blog_id]
		entry.save
		redirect_to blog_path(entry.blog)
	end

	def show
		@entry = Entry.find(params[:id])
	end

	def destroy
		@entry = Entry.find(params[:id])
		@entry.destroy
		redirect_to blog_path(@entry.blog)
	end

	def edit; end

	private
	def entry_params
		params.require(:entry).permit(:title, :body, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/index.html.haml
.content
	%ul.btn
		%li.active ボタン1
		%li ボタン2
		%li ボタン3
	%p Listing blogs
%table.title_box
	%th
		%tr
			%th Title
		- @blogs.each do |blog|
			%tr
				%td= blog.title.html_safe
				%td= link_to "Show", blog_path(blog)
				%td= link_to "Edit", edit_blog_path(blog)
				%td= link_to "Destroy", blog_path(blog), method: :delete
= search_form_for @q do |f|
	= f.label :title_cont, "タイトルを含む"
	= f.search_field :title_cont
	= f.submit "検索"
= link_to "New Blog", new_blog_path
= link_to "csv出力", blogs_path(format: :csv)

app/views/blogs/new.html.haml
.form_content
	%p New blog
	%h3 Title
	= simple_form_for Blog.new do |f|
		= f.input :title
		= f.button :submit, 'Save'
= link_to "Back", :back

app/views/blogs/show.html.haml
%p Title: #{@blog.title}
= link_to "Edit"
= link_to "Back", root_path
%p Listing entries
%table.blogs_content
	%thead
		%tr
			%th Title
			%th Body
	%tbody
		- @blog.entries.each do |entry|
			%tr
				%td= entry.title
				%td= entry.body
				%td= link_to "Show", blog_entry_path(@blog, entry)
				%td= link_to "Edit", edit_blog_entry_path(@blog, entry)
				%td= link_to "Destroy", blog_entry_path(@blog, entry), method: :delete
= link_to "New Entry", new_blog_entry_path(@blog)

app/views/comments/_new.html.haml
%p New comment
%span Body
= simple_form_for(Comment.new, scope: :comment, method: :post, url: blog_entry_comments_path(entry_id: @entry)) do |f|
	= f.input :body
	= f.button :submit, 'Save'

app/views/entries/new.html.haml
.form_content
	%p New entry:
	= simple_form_for(Entry.new, scope: :entry, method: :post, url: blog_entries_path) do |f|
		= f.input :title
		= f.input :body
		= f.file_field :image
		= f.button :submit, 'Save'
= link_to "Back", :back

app/views/entries/show.html.haml
%p= @entry.blog.title
%p #{@entry.title}
%p #{@entry.body}
= image_tag "#{@entry.image}"
= link_to "Edit"
= link_to "Back", blog_path(@entry.blog)
%p Listing comments
%table.comments_content
	%tr
		%th Body
	- @entry.comments.each do |comment|
		- if comment.status == "approved"
			%tr
				%td= comment.body
				%td
				%td= link_to "Destroy", blog_entry_comment_path(@entry.blog, @entry, comment),method: :delete
		- else
			%tr
				%td= "承認待ち"
				%td= link_to "Approved", blog_entry_comment_path(@entry.blog, @entry, comment), method: :patch
				%td= link_to "Destroy", blog_entry_comment_path(@entry.blog, @entry, comment), method: :delete
= render 'comments/new'

app/views/layouts/_footer.html.haml
%p SonicGarden Inc.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TrialTest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    = render 'layouts/footer'